# Generated by Django 3.0.4 on 2022-04-24 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='vendor',
            new_name='restaurant',
        ),
    ]
