# Generated by Django 3.0.4 on 2022-04-24 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='vendor_paid',
            new_name='restaurant_paid',
        ),
    ]
